Fix Errrors And release New Version
idpay/idpay-for-contact-form-7 pull request #13
Opened 2022-06-08 12:53 UTC by MimDeveloperTv

Please code review and merge

2022-06-18 11:33 UTC, meysamrazmi reviewed
final

2022-06-18 11:33 UTC, meysamrazmi commented on readme.txt
> +
```suggestion
= 2.2.0, June 13, 2022 =
* Improve sanitizing
* Change redirecting behavior after payment

```

2022-06-18 11:33 UTC, meysamrazmi commented on readme.txt
>  Tested up to: 5.7
```suggestion
Tested up to: 6.0
```

2022-06-18 11:33 UTC, meysamrazmi commented on includes/Plugin.php
> +        if (version_compare($version, '2.1.1') < 0) {
you didn't add another else so you won't create your new table for those who are already using the plugin

@MimDeveloperTv

2022-06-18 11:33 UTC, meysamrazmi commented on includes/Plugin.php
> +               id bigint(11) NOT NULL AUTO_INCREMENT,
lint problem

2022-06-18 11:33 UTC, meysamrazmi commented on includes/Payment/Result.php
> +            return fetch_callback_response($wpdb, $_GET['order_id']);
You don't need to pass the db variable to the function

2022-06-18 11:33 UTC, meysamrazmi commented on includes/Payment/Result.php
> +        if(!empty( $_GET['order_id'])) {
use a more accurate variable name for this plugin. `order_id` is so general

2022-06-18 11:33 UTC, meysamrazmi commented on includes/Functions.php
> +        $db->insert( $db->prefix . $tableName, $row, array('%s','%s','%s','%s') );
you didn't care about linting in every place

2022-06-18 11:33 UTC, meysamrazmi commented on includes/Functions.php
> +function create_callback_response($db, $order_id, $trans_id, $track_id, $status, $message)
no need to pass `$db` to this function. this is a global variable

2022-06-18 11:33 UTC, meysamrazmi commented on includes/Functions.php
> +{    $tableName = 'cf7_callbacks';
WTF?

2022-06-18 11:33 UTC, meysamrazmi commented on includes/Callback.php
> +    wp_redirect( add_query_arg([], $value['return'] ) );
why you didn't set the order_id in query argumants

2022-06-18 11:33 UTC, meysamrazmi commented on includes/Functions.php
> +            ]),
there is no need to save these ids in this table. this table is being used just for redirecting

2022-06-18 11:33 UTC, meysamrazmi commented on includes/Functions.php
> +            'message' => json_encode($message),
`$message` is already a string. why do you encode it here?

2022-06-19 08:46 UTC, meysamrazmi requested changes, later dismissed
@MimDeveloperTv

2022-06-19 08:46 UTC, meysamrazmi commented on includes/Callback.php
> +        create_callback_response($order_id,$status, $message);
`$order_id,$status`
lint

2022-06-19 08:46 UTC, meysamrazmi commented on includes/Callback.php
> +            create_callback_response($wpdb, $order_id, $trans_id, $track_id, $status, $message);
you didn't pass correct parameters to the function

2022-06-19 08:46 UTC, meysamrazmi commented on includes/Callback.php
> +        create_callback_response($order_id,$status, $message);
lint

2022-06-19 08:46 UTC, meysamrazmi commented on includes/Functions.php
> +            'response' => json_encode(['status' => $status]),
I said you should change the response to status. it's not necessary to save it as json

2022-06-19 08:46 UTC, meysamrazmi commented on includes/Payment/Payment.php
> +            wp_redirect(add_query_arg('idpay_error', __('Amount can not be empty', 'idpay-contact-form-7')));
these redirects should have been changed too

2022-06-19 08:46 UTC, meysamrazmi commented on includes/Payment/Payment.php
> +            wp_redirect(add_query_arg('idpay_error', $error));
this one too

2022-06-19 08:46 UTC, meysamrazmi commented on includes/Payment/Payment.php
> +            wp_redirect(add_query_arg('idpay_error', $error));
this one too

2022-06-19 08:46 UTC, meysamrazmi commented on includes/Payment/Payment.php
> +    }
use the functions.php instead

2022-06-19 08:46 UTC, meysamrazmi commented on includes/Payment/Result.php
> +        if (!empty($_GET['order_id'])) {
as I said you should use a more specific term instead of `order_id`

2022-06-19 08:46 UTC, meysamrazmi commented on includes/Plugin.php
> +        if(version_compare($version, '2.2.0') < 0)
Did you even test it???
the version you are checking should be the previous one

2022-06-19 08:46 UTC, meysamrazmi commented on readme.txt
> +
there is extra space before the line

2022-10-02 14:20 UTC, mohammad-malekpaeen commented on includes/Callback.php
> +    wp_redirect( add_query_arg([], $value['return'] ) );
ok

2022-10-02 14:20 UTC, mohammad-malekpaeen commented on includes/Functions.php
> +function create_callback_response($db, $order_id, $trans_id, $track_id, $status, $message)
ok

2022-10-02 14:20 UTC, mohammad-malekpaeen commented on includes/Callback.php
> +            create_callback_response($wpdb, $order_id, $trans_id, $track_id, $status, $message);
ok

2022-10-02 14:20 UTC, mohammad-malekpaeen commented on includes/Callback.php
> +        create_callback_response($order_id,$status, $message);
ok

2022-10-02 14:20 UTC, mohammad-malekpaeen commented on includes/Callback.php
> +        create_callback_response($order_id,$status, $message);
ok

2022-10-02 14:20 UTC, mohammad-malekpaeen commented on includes/Functions.php
> +            'response' => json_encode(['status' => $status]),
ok

2022-10-02 14:20 UTC, mohammad-malekpaeen commented on includes/Payment/Payment.php
> +            wp_redirect(add_query_arg('idpay_error', __('Amount can not be empty', 'idpay-contact-form-7')));
ok

2022-10-02 14:21 UTC, MimDeveloperTv reviewed
ok tanks

2022-10-02 14:25 UTC, merged